# Generated by Django 4.1.3 on 2024-01-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.RemoveField(
            model_name='recentwork',
            name='image',
        ),
        migrations.AddField(
            model_name='recentwork',
            name='description',
            field=models.TextField(default=None, verbose_name='Work Detail'),
        ),
    ]
